name: Release

on:
  push:
    branches:
    - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-ecosystem/action-regex-match@v2
      id: version-number
      with:
        text: ${{ github.event.head_commit.message }}
        regex: '^Release (\d+\.\d+\.\d+)'
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine
    - name: Set Prod conf.ini
      run: |
        mv mentat/resources/conf/conf-prod.ini mentat/resources/conf/conf.ini
    - name: Github Release
      if: ${{ steps.version-number.outputs.match != '' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version-number.outputs.group1 }}
    - name: PyPi Release
      if: ${{ steps.version-number.outputs.match != '' }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
    - name: Brew Release
      if: ${{ steps.version-number.outputs.match != '' }}
      uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{ secrets.TOKEN_FOR_BREW }}
        formula: mentat